IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID('p_TARIFA_TRANSFERENCIA_i'))
BEGIN
    DROP PROCEDURE p_TARIFA_TRANSFERENCIA_i
END
GO
CREATE PROCEDURE p_TARIFA_TRANSFERENCIA_i
@CONTA_ID INT,
@VALOR DECIMAL
AS
BEGIN
	DECLARE @ERROR_MESSAGE VARCHAR(MAX)

	BEGIN TRY
		BEGIN TRANSACTION
			IF NOT EXISTS(SELECT 1 FROM CONTA WHERE CONTA_ID = @CONTA_ID)
				RAISERROR('CONTA NÃO ENCONTRADA!', 11, 1)

			INSERT INTO CONTA_TRANSACAO (TRANSACAO_DATA, CONTA_ID, TRANSACAO_TIPO_COD, 
				QUANTIA, DATA_FUNDO_DISPONIVEL)
			SELECT GETDATE(), @CONTA_ID, 'TARIFA', -@VALOR, GETDATE()

			UPDATE CONTA SET SALDO_DISPONIVEL = SALDO_DISPONIVEL - @VALOR WHERE CONTA_ID = @CONTA_ID;
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRAN

		SELECT @ERROR_MESSAGE = ERROR_MESSAGE();
		RAISERROR(@ERROR_MESSAGE, 1, 1)
	END CATCH

END
GO